version: '2'

services:
  
  rabbit:
    image: rabbitmq:management-alpine
    ports:
      - 8080:15672
      - 5672

  php:
    build: .
    working_dir: /var/www
    volumes:
      - .:/var/www
      